# Generated by Django 5.0.6 on 2026-04-24 11:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Название')),
                ('muscle_group', models.CharField(max_length=80, verbose_name='Группа мышц')),
                ('exercise_type', models.CharField(max_length=80, verbose_name='Тип упражнения')),
                ('technique_description', models.TextField(blank=True, verbose_name='Описание техники')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'упражнение',
                'verbose_name_plural': 'упражнения',
                'ordering': ['muscle_group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Название')),
                ('calories_per_100g', models.DecimalField(decimal_places=1, max_digits=7, verbose_name='Ккал на 100 г')),
                ('protein_per_100g', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Белки на 100 г')),
                ('fat_per_100g', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Жиры на 100 г')),
                ('carbs_per_100g', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Углеводы на 100 г')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название дня')),
                ('day_number', models.PositiveSmallIntegerField(default=1, verbose_name='Номер дня')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'тренировочный день',
                'verbose_name_plural': 'тренировочные дни',
                'ordering': ['day_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рост, см')),
                ('goal', models.CharField(choices=[('weight_loss', 'Похудение'), ('muscle_gain', 'Набор мышечной массы'), ('maintenance', 'Поддержание формы'), ('endurance', 'Улучшение выносливости'), ('recovery', 'Восстановление')], default='maintenance', max_length=32, verbose_name='Цель')),
                ('training_level', models.CharField(blank=True, max_length=80, verbose_name='Уровень подготовки')),
                ('health_limitations', models.TextField(blank=True, verbose_name='Ограничения по здоровью')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('paused', 'Пауза'), ('archived', 'Архив')], default='active', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'профиль клиента',
                'verbose_name_plural': 'профили клиентов',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='CompletedWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выполнения')),
                ('mood', models.CharField(blank=True, max_length=120, verbose_name='Самочувствие')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_workouts', to='club.clientprofile', verbose_name='Клиент')),
                ('workout_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_workouts', to='club.workoutday', verbose_name='Тренировочный день')),
            ],
            options={
                'verbose_name': 'выполненная тренировка',
                'verbose_name_plural': 'выполненные тренировки',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField(verbose_name='Дата')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('snack', 'Перекус')], max_length=16, verbose_name='Прием пищи')),
                ('comment', models.CharField(blank=True, max_length=240, verbose_name='Комментарий')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='club.clientprofile', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'прием пищи',
                'verbose_name_plural': 'приемы пищи',
                'ordering': ['meal_date', 'meal_type'],
                'unique_together': {('client', 'meal_date', 'meal_type')},
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120, verbose_name='Тип абонемента')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('visits_total', models.PositiveIntegerField(default=0, verbose_name='Всего посещений')),
                ('visits_left', models.PositiveIntegerField(default=0, verbose_name='Осталось посещений')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('expired', 'Завершен'), ('frozen', 'Заморожен')], default='active', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='club.clientprofile', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'абонемент',
                'verbose_name_plural': 'абонементы',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, max_length=140, verbose_name='Свое блюдо')),
                ('weight_grams', models.DecimalField(decimal_places=1, max_digits=7, verbose_name='Вес, г')),
                ('calories', models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='Ккал')),
                ('protein', models.DecimalField(decimal_places=1, default=0, max_digits=7, verbose_name='Белки')),
                ('fat', models.DecimalField(decimal_places=1, default=0, max_digits=7, verbose_name='Жиры')),
                ('carbs', models.DecimalField(decimal_places=1, default=0, max_digits=7, verbose_name='Углеводы')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='club.meal', verbose_name='Прием пищи')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_items', to='club.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'позиция питания',
                'verbose_name_plural': 'позиции питания',
            },
        ),
        migrations.CreateModel(
            name='ProgressRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Вес')),
                ('waist', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Талия')),
                ('chest', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Грудь')),
                ('hips', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Бедра')),
                ('comment', models.CharField(blank=True, max_length=240, verbose_name='Комментарий')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='club.clientprofile', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'запись прогресса',
                'verbose_name_plural': 'записи прогресса',
                'ordering': ['record_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('specialization', models.CharField(max_length=160, verbose_name='Специализация')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='Стаж, лет')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('paused', 'Пауза'), ('archived', 'Архив')], default='active', max_length=16, verbose_name='Статус')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'профиль тренера',
                'verbose_name_plural': 'профили тренеров',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='TrainerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_type', models.CharField(choices=[('profile', 'Профиль'), ('workout', 'Тренировка'), ('nutrition', 'Питание'), ('progress', 'Прогресс')], default='profile', max_length=20, verbose_name='Раздел')),
                ('related_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID связанной записи')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_comments', to='club.clientprofile', verbose_name='Клиент')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='club.trainerprofile', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'комментарий тренера',
                'verbose_name_plural': 'комментарии тренера',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NutritionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories_target', models.PositiveIntegerField(verbose_name='Ккал')),
                ('protein_target', models.PositiveIntegerField(verbose_name='Белки')),
                ('fat_target', models.PositiveIntegerField(verbose_name='Жиры')),
                ('carbs_target', models.PositiveIntegerField(verbose_name='Углеводы')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_targets', to='club.clientprofile', verbose_name='Клиент')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutrition_targets', to='club.trainerprofile', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'норма питания',
                'verbose_name_plural': 'нормы питания',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='club.trainerprofile', verbose_name='Тренер'),
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets_count', models.PositiveSmallIntegerField(default=3, verbose_name='Подходы')),
                ('reps_count', models.PositiveSmallIntegerField(default=12, verbose_name='Повторения')),
                ('recommended_weight', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Рекомендуемый вес')),
                ('rest_seconds', models.PositiveSmallIntegerField(default=60, verbose_name='Отдых, сек')),
                ('comment', models.CharField(blank=True, max_length=240, verbose_name='Комментарий')),
                ('order_number', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_entries', to='club.exercise', verbose_name='Упражнение')),
                ('workout_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='club.workoutday', verbose_name='Тренировочный день')),
            ],
            options={
                'verbose_name': 'упражнение в плане',
                'verbose_name_plural': 'упражнения в плане',
                'ordering': ['order_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompletedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_sets', models.PositiveSmallIntegerField(default=0, verbose_name='Фактические подходы')),
                ('actual_reps', models.PositiveSmallIntegerField(default=0, verbose_name='Фактические повторения')),
                ('actual_weight', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Фактический вес')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('comment', models.CharField(blank=True, max_length=240, verbose_name='Комментарий')),
                ('completed_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='club.completedworkout', verbose_name='Тренировка')),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_entries', to='club.workoutexercise', verbose_name='Плановое упражнение')),
            ],
            options={
                'verbose_name': 'выполненное упражнение',
                'verbose_name_plural': 'выполненные упражнения',
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Название')),
                ('goal', models.CharField(choices=[('weight_loss', 'Похудение'), ('muscle_gain', 'Набор мышечной массы'), ('maintenance', 'Поддержание формы'), ('endurance', 'Улучшение выносливости'), ('recovery', 'Восстановление')], max_length=32, verbose_name='Цель')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('completed', 'Завершен')], default='active', max_length=16, verbose_name='Статус')),
                ('is_template', models.BooleanField(default=False, verbose_name='Шаблон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='club.clientprofile', verbose_name='Клиент')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_plans', to='club.trainerprofile', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'тренировочный план',
                'verbose_name_plural': 'тренировочные планы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='workoutday',
            name='workout_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='club.workoutplan', verbose_name='План'),
        ),
    ]
