# Generated by Django 5.0.6 on 2026-05-23 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_managementaianalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('running', 'Анализируется'), ('done', 'Готово'), ('failed', 'Ошибка')], default='queued', max_length=16, verbose_name='Статус')),
                ('provider', models.CharField(max_length=40, verbose_name='Провайдер')),
                ('model', models.CharField(max_length=120, verbose_name='Модель')),
                ('payload', models.JSONField(default=dict, verbose_name='Данные тренера')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='Результат')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начат')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершен')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_ai_analyses', to=settings.AUTH_USER_MODEL, verbose_name='Запросил')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='club.trainerprofile', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'ИИ-ассистент тренера',
                'verbose_name_plural': 'ИИ-ассистенты тренера',
                'ordering': ['-created_at'],
            },
        ),
    ]
