# Generated by Django 5.0.6 on 2026-05-23 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_traineraianalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='Начало')),
                ('end_at', models.DateTimeField(verbose_name='Окончание')),
                ('note', models.CharField(blank=True, max_length=240, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedule_slots', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='club.trainerprofile', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'слот расписания',
                'verbose_name_plural': 'слоты расписания',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booked', 'Записано'), ('cancelled', 'Отменено'), ('completed', 'Проведено')], default='booked', max_length=16, verbose_name='Статус')),
                ('booked_at', models.DateTimeField(auto_now_add=True, verbose_name='Записан')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменен')),
                ('cancel_reason', models.CharField(blank=True, max_length=240, verbose_name='Причина отмены')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_training_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Отменил')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_appointments', to='club.clientprofile', verbose_name='Клиент')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='club.scheduleslot', verbose_name='Слот')),
            ],
            options={
                'verbose_name': 'запись на тренировку',
                'verbose_name_plural': 'записи на тренировки',
                'ordering': ['slot__start_at'],
            },
        ),
    ]
