# Generated by Django 5.0.6 on 2026-05-23 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_scheduleslot_trainingappointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trainingappointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'booked')), fields=('slot',), name='unique_booked_appointment_per_slot'),
        ),
    ]
