# Generated by Django 5.0.6 on 2026-05-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_clientaianalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('planned', 'Запланирован'), ('expired', 'Завершен'), ('frozen', 'Заморожен')], default='active', max_length=16, verbose_name='Статус'),
        ),
    ]
