# Generated by Django 5.0.6 on 2026-05-25 10:06

import django.db.models.deletion
from django.db import migrations, models


def make_catalog_names_unique(apps, schema_editor):
    for model_name in ("Exercise", "Product"):
        model = apps.get_model("club", model_name)
        seen = {}
        for item in model.objects.order_by("name", "id").only("id", "name"):
            base_name = item.name or f"{model_name} {item.pk}"
            if base_name not in seen:
                seen[base_name] = 1
                continue

            seen[base_name] += 1
            suffix_number = seen[base_name]
            while True:
                suffix = f" ({suffix_number})"
                candidate = f"{base_name[:140 - len(suffix)]}{suffix}"
                if not model.objects.filter(name=candidate).exclude(pk=item.pk).exists():
                    break
                suffix_number += 1

            item.name = candidate
            item.save(update_fields=["name"])


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_alter_membership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedworkout',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_workout', to='club.trainingappointment', verbose_name='Запись на тренировку'),
        ),
        migrations.RunPython(make_catalog_names_unique, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=140, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=140, unique=True, verbose_name='Название'),
        ),
    ]
