# Generated by Codex on 2026-06-05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0009_completedworkout_appointment_alter_exercise_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainerReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (5, "5 - отлично"),
                            (4, "4 - хорошо"),
                            (3, "3 - нормально"),
                            (2, "2 - есть замечания"),
                            (1, "1 - плохо"),
                        ],
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Оценка",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Заголовок")),
                ("text", models.TextField(verbose_name="Текст отзыва")),
                ("is_published", models.BooleanField(default=True, verbose_name="Опубликован")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлен")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_reviews",
                        to="club.clientprofile",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_reviews",
                        to="club.trainerprofile",
                        verbose_name="Тренер",
                    ),
                ),
            ],
            options={
                "verbose_name": "оценка тренера",
                "verbose_name_plural": "оценки тренеров",
                "ordering": ["-created_at"],
            },
        ),
    ]
