# Generated by Codex on 2026-06-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0010_trainerreview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeightForecastAnalysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "В очереди"),
                            ("running", "Анализируется"),
                            ("done", "Готово"),
                            ("failed", "Ошибка"),
                        ],
                        default="queued",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                ("provider", models.CharField(max_length=40, verbose_name="Провайдер")),
                ("model", models.CharField(max_length=120, verbose_name="Модель")),
                ("payload", models.JSONField(default=dict, verbose_name="Данные прогноза")),
                ("result", models.JSONField(blank=True, null=True, verbose_name="Прогноз")),
                ("error", models.TextField(blank=True, verbose_name="Ошибка")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="Начат")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="Завершен")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_forecasts",
                        to="club.clientprofile",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_forecast_analyses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Запросил",
                    ),
                ),
            ],
            options={
                "verbose_name": "ИИ-прогноз веса",
                "verbose_name_plural": "ИИ-прогнозы веса",
                "ordering": ["-created_at"],
            },
        ),
    ]
