from django.urls import path

from . import views

urlpatterns = [
    path("", views.landing, name="landing"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("reviews/", views.reviews_page, name="reviews"),
    path("schedule/", views.schedule_page, name="schedule"),
    path("schedule/slots/<int:pk>/book/", views.schedule_slot_book, name="schedule_slot_book"),
    path("schedule/slots/<int:pk>/remove/", views.schedule_slot_deactivate, name="schedule_slot_deactivate"),
    path("schedule/appointments/<int:pk>/cancel/", views.schedule_appointment_cancel, name="schedule_appointment_cancel"),
    path("schedule/appointments/<int:pk>/complete/", views.schedule_appointment_complete, name="schedule_appointment_complete"),
    path("meal-items/<int:pk>/delete/", views.meal_item_delete, name="meal_item_delete"),
    path("progress-records/<int:pk>/delete/", views.progress_record_delete, name="progress_record_delete"),
    path("workouts/<int:pk>/delete/", views.completed_workout_delete, name="completed_workout_delete"),
    path("clients/", views.clients_list, name="clients_list"),
    path("clients/new/", views.client_create, name="client_create"),
    path("clients/<int:pk>/", views.client_detail, name="client_detail"),
    path("clients/<int:pk>/edit/", views.client_edit, name="client_edit"),
    path("clients/<int:client_id>/memberships/new/", views.membership_create, name="membership_create"),
    path("memberships/<int:pk>/edit/", views.membership_edit, name="membership_edit"),
    path("clients/<int:client_id>/plans/new/", views.workout_plan_create, name="workout_plan_create"),
    path("plans/<int:pk>/", views.workout_plan_detail, name="workout_plan_detail"),
    path("plans/<int:plan_id>/days/new/", views.workout_day_create, name="workout_day_create"),
    path("days/<int:day_id>/exercises/new/", views.workout_exercise_create, name="workout_exercise_create"),
    path("days/<int:day_id>/complete/", views.complete_workout, name="complete_workout"),
    path("nutrition/", views.nutrition_page, name="nutrition"),
    path("clients/<int:client_id>/nutrition/", views.nutrition_page, name="nutrition_client"),
    path("clients/<int:client_id>/nutrition-target/", views.nutrition_target_set, name="nutrition_target_set"),
    path("progress/", views.progress_page, name="progress"),
    path("clients/<int:client_id>/progress/", views.progress_page, name="progress_client"),
    path("clients/<int:client_id>/weight-forecast/start/", views.weight_forecast_analysis_start, name="weight_forecast_analysis_start"),
    path("weight-forecast/<int:pk>/status/", views.weight_forecast_analysis_status, name="weight_forecast_analysis_status"),
    path("recommendations/", views.recommendations_page, name="recommendations"),
    path("clients/<int:client_id>/recommendations/", views.recommendations_page, name="recommendations_client"),
    path("clients/<int:client_id>/comments/new/", views.comment_create, name="comment_create"),
    path("trainers/", views.trainers_list, name="trainers_list"),
    path("trainers/new/", views.trainer_create, name="trainer_create"),
    path("trainers/<int:pk>/edit/", views.trainer_edit, name="trainer_edit"),
    path("exercises/", views.exercises_list, name="exercises_list"),
    path("products/", views.products_list, name="products_list"),
    path("dashboards/", views.admin_dashboards, name="admin_dashboards"),
    path("dashboards/ai-analysis/start/", views.management_ai_analysis_start, name="management_ai_analysis_start"),
    path("dashboards/ai-analysis/<int:pk>/status/", views.management_ai_analysis_status, name="management_ai_analysis_status"),
    path("trainer-ai/start/", views.trainer_ai_analysis_start, name="trainer_ai_analysis_start"),
    path("trainer-ai/<int:pk>/status/", views.trainer_ai_analysis_status, name="trainer_ai_analysis_status"),
    path("client-ai/start/", views.client_ai_analysis_start, name="client_ai_analysis_start"),
    path("client-ai/<int:pk>/status/", views.client_ai_analysis_status, name="client_ai_analysis_status"),
    path("reports/", views.reports_index, name="reports"),
]
